export const fontMapping = {
    "Alfa Slab One": "/assets/custom-fonts/embedded/alfa_slab_one.css",
    "Cherry Swash": "/assets/custom-fonts/embedded/cherry_swash.css",
    "Caveat Brush": "/assets/custom-fonts/embedded/caveat_brush.css",
    "Heebo": "/assets/custom-fonts/embedded/heebo.css",
    "Carter One": "/assets/custom-fonts/embedded/carter_one.css",
    "Permanent Marker": "/assets/custom-fonts/embedded/permanent_marker.css",
    "Josefin Sans": "/assets/custom-fonts/embedded/josefin_sans.css",
    "Knewave": "/assets/custom-fonts/embedded/knewave.css",
    "Nunito": "/assets/custom-fonts/embedded/nunito.css",
    "Caveat": "/assets/custom-fonts/embedded/caveat.css",
    "Indie-Flower": "/assets/custom-fonts/embedded/indie_flower.css",
    "Single-Day": "/assets/custom-fonts/embedded/single_day.css",
    "KaTeX_AMS": "/assets/custom-fonts/embedded/katex_ams.css",
    "KaTeX_Caligraphic": "/assets/custom-fonts/embedded/katex_caligraphic.css",
    "KaTeX_Fraktur": "/assets/custom-fonts/embedded/katex_fraktur.css",
    "KaTeX_Main": "/assets/custom-fonts/embedded/katex_main.css",
    "KaTeX_Math": "/assets/custom-fonts/embedded/katex_math.css",
    "KaTeX_SansSerif": "/assets/custom-fonts/embedded/katex_sansserif.css",
    "KaTeX_Script": "/assets/custom-fonts/embedded/katex_script.css",
    "KaTeX_Size1": "/assets/custom-fonts/embedded/katex_size1.css",
    "KaTeX_Size2": "/assets/custom-fonts/embedded/katex_size2.css",
    "KaTeX_Size3": "/assets/custom-fonts/embedded/katex_size3.css",
    "KaTeX_Size4": "/assets/custom-fonts/embedded/katex_size4.css"
};
