/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import {stopAllAnimationsForEntityInAnimationRegistry} from '../../animations/AnimationRegistry';

export default {
    name: 'Stop All Animations',

    description: 'Stops all animations that were either created in the background or generated by another event',

    args: {},

    execute(entity, args, schemeContainer, userEventBus, resultCallback) {
        if (entity && entity.id) {
            stopAllAnimationsForEntityInAnimationRegistry(schemeContainer.editorId, entity.id);
        }
        resultCallback();
    }
};

