name: Pie chart
description: ""
args:
    data:
      group: Data
      name: Data
      singular: entry
      type: array
      value:
        - id: 44zYCq52M
          name: Data 1
          value: 10
          color: "#355E97FF"
        - id: 6IDE7Ij4
          name: Data 2
          value: 40
          color: "#975E35FF"
        - id: iByb3V9kZTu
          name: Data 3
          value: 5
          color: "#35975EFF"
      args:
        name         : {type: "string", value: "Data ##IDX##", name: "Name"}
        value        : {type: "number", value: 10, min: 0, name: "Value"}
        color        : {type: "color", value: "#355E97FF", name: "Color"}

    background      : {group: "Style", type: 'advanced-color', value: "#E8E8E9FF", name: 'Background'}
    strokeColor     : {group: "Style", type: "color", value: "#C7C7C7FF", name: "Stroke color"}
    strokeSize      : {group: "Style", type: "number", value: 1, name: "Stroke size"}
    sliceStrokeColor: {group: "Style", type: "color", value: "#C7C7C7FF", name: "Stroke color"}
    sliceStrokeSize : {group: "Style", type: "number", value: 1, name: "Stroke size"}
    cornerRadius    : {group: "Style", type: "number", value: 5, name: "Corner radius", min: 0}
    padding         : {group: "Style", type: 'number', value: 20, name: 'Padding'}
    initialAngle    : {group: "Style", type: 'number', value: 0, min: 0, max: 360, name: 'Initial Angle'}

    titleFontSize: {group: 'Text', type: 'number', value: 16, name: 'Title font size'}
    font         : {group: 'Text', type: font, value: Arial, name: Font}

    hasLegend     : {group: 'Legend', type: 'boolean', value: true, name: 'Legend'}
    fontSize      : {group: 'Legend', type: 'number', value: 14, name: 'Font size'}
    fontColor     : {group: 'Legend', type: color, value: "#333333FF", name: Label color}
    legendSpacing : {group: 'Legend', type: 'number', value: 5, min: 0, softMax: 20, name: 'Legend spacing'}
    iconSize      : {group: 'Legend', type: 'number', value: 20, min: 1, softMax: 50, name: 'Icon size'}
    iconCornerSize: {group: 'Legend', type: 'number', value: 5, min: 0, softMax: 50, name: 'Icon corner size'}



import:
    - ./src/pie-chart.sch
    - ./src/pie-chart-animations.sch

item:
  id: root
  name: Pie chart
  shape: rect
  shapeProps:
    fill: $background
    strokeColor: $strokeColor
    strokeSize: $strokeSize
    cornerRadius: $cornerRadius
  locked: false
  area:
    x: 0
    y: 0
    w: $width
    h: $height
  functions:
  - id: func-change-pie
    name: Change Pie chart
    description: Updates the values in the Pie chart with animation
    args:
    - id: arg-index
      name: values
      value: "10, 4, 5, 7, 2"
      type: string
      description: Comma separated list of values
    props:
      initScript: $changeAnimationInitScript
      script: $changeAnimationLoopScript
      endScript: $changeAnimationEndScript
      animated: true
      animationType: "animation"
      animationDuration: 0.5
      transition: "ease-out"
      inBackground: true

  childItems:
  - $-foreach: {source: "slices", it: "slice"}
    id: $`slice-${slice.id}"`
    name: $slice.name
    shape: pie_segment
    tags:
      - pie-chart-slice
    args:
      customVars:
        name   : $slice.name
        value  : $slice.value
        percent: $slice.percent
        idx    : $slice.idx
    area:
      x: $padding
      y: $padding
      w: $chartWidth
      h: $chartHeight
      r: $slice.angle

    shapeProps:
      percent: $slice.percent
      fill: {type: solid, color: $slice.color}
      strokeSize: $strokeSize
      strokeColor: $strokeColor

  - $-foreach: {source: sliceLabels, it: label}
    id: $label.id
    name: $label.text
    shape: none
    opacity: $label.opacity
    area:
      x: $label.x
      y: $label.y
      w: $label.w
      h: $label.h
    args:
      templateForceText: true
    textSlots:
      body:
        text: $label.text
        font: $font
        fontSize: $label.fontSize
        color: $fontColor

  - id: legend-container
    name: Legend
    shape: none
    area:
      x: $legend.x
      y: $legend.y
      w: $legend.w
      h: $legend.h
    clip: true
    childItems:
    - $-foreach: {source: legend.entries, it: entry}
      id: $`legend-entry-icon-${entry.id}`
      name: $`Icon ${entry.name}`
      shape: rect
      area:
        x: $entry.x
        y: ${ entry.y + entry.h / 2 - iconSize/2 }
        w: $iconSize
        h: $iconSize
      shapeProps:
        fill: {type: solid, color: $entry.color}
        cornerRadius: $iconCornerSize
        strokeSize: 0

    - $-foreach: {source: legend.entries, it: entry}
      id: $`legend-entry-label-${entry.id}`
      name: $`Label ${entry.name}`
      shape: none
      area:
        x: ${ entry.x + 30 }
        y: $entry.y
        w: $entry.w
        h: $entry.h
      args:
        templateForceText: true
      textSlots:
        body:
          text: $entry.name
          fontSize: $fontSize
          font: $font
          color: $fontColor
          valign: middle
          halign: left

