name: Pie chart
description: ""
args:
    data:
      group: Data
      name: Data
      singular: entry
      type: array
      value:
        - id: 44zYCq52M
          name: Data 1
          value: 10
          color: "#CD7BDBFF"
        - id: 6IDE7Ij4
          name: Data 2
          value: 40
          color: "#65DC8BFF"
        - id: iByb3V9kZTu
          name: Data 3
          value: 5
          color: "#518DD7FF"
      args:
        name         : {type: "string", value: "Data ##IDX##", name: "Name"}
        value        : {type: "number", value: 10, min: 0, name: "Value"}
        color        : {type: "color", value: "#355E97FF", name: "Color"}

    background      : {group: "Style", type: 'advanced-color', value: {type: solid, color: "#E8E8E9FF"}, name: 'Background'}
    strokeColor     : {group: "Style", type: "color", value: "#C7C7C7FF", name: "Stroke color"}
    strokeSize      : {group: "Style", type: "number", value: 1, name: "Stroke size"}
    sliceStrokeColor: {group: "Style", type: "color", value: "#C7C7C7FF", name: "Stroke color"}
    sliceStrokeSize : {group: "Style", type: "number", value: 1, name: "Stroke size"}
    cornerRadius    : {group: "Style", type: "number", value: 5, name: "Corner radius", min: 0}
    padding         : {group: "Style", type: 'number', value: 20, name: 'Padding'}
    initialAngle    : {group: "Style", type: 'number', value: 0, min: 0, max: 360, name: 'Initial Angle'}

    titleFontSize: {group: 'Text', type: 'number', value: 16, name: 'Title font size'}
    font         : {group: 'Text', type: font, value: Arial, name: Font}
    fontSize     : {group: 'Text', type: 'number', value: 14, name: 'Font size'}
    hasLabels    : {group: 'Text', type: 'boolean', value: true, name: 'Labels'}

    hasLegend     : {group: 'Legend', type: 'boolean', value: true, name: 'Legend'}
    fontColor     : {group: 'Legend', type: color, value: "#333333FF", name: Label color}
    legendSpacing : {group: 'Legend', type: 'number', value: 5, min: 0, softMax: 20, name: 'Legend spacing'}
    iconSize      : {group: 'Legend', type: 'number', value: 20, min: 1, softMax: 50, name: 'Icon size'}
    iconCornerSize: {group: 'Legend', type: 'number', value: 5, min: 0, softMax: 50, name: 'Icon corner size'}

preview: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhodG1sPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmlld0JveD0iLTIgLTIgMzI0IDMyNCI+PGRlZnM+PHN0eWxlPgovKioqKioqKioqKioqKioqKioqIExhbmd1YWdlIE1hcmt1cCAqKioqKioqKioqKioqKiovCgouc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtc3Ryb25nLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1lbXBoYXNpc3tjb2xvcjojYThhOGEyfQouc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtYnVsbGV0LC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1xdW90ZSwuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtbGluaywuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtbnVtYmVyLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1yZWdleHAsLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLWxpdGVyYWx7Y29sb3I6IzY4OTZiYX0KLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLWNvZGUsLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLXNlbGVjdG9yLWNsYXNze2NvbG9yOiNhNmUyMmV9Ci5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1lbXBoYXNpc3tmb250LXN0eWxlOml0YWxpY30KLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLWtleXdvcmQsLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLXNlbGVjdG9yLXRhZywuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtc2VjdGlvbiwuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtYXR0cmlidXRlLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1uYW1lLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy12YXJpYWJsZXtjb2xvcjojY2I3ODMyfQouc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtcGFyYW1ze2NvbG9yOiNiZGM3OTF9Ci5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1zdHJpbmd7Y29sb3I6IzVhODg0MH0KLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLXN1YnN0LC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy10eXBlLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1idWlsdF9pbiwuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtYnVpbHRpbi1uYW1lLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1zeW1ib2wsLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLXNlbGVjdG9yLWlkLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1zZWxlY3Rvci1hdHRyLAouc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtc2VsZWN0b3ItcHNldWRvLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy10ZW1wbGF0ZS10YWcsLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLXRlbXBsYXRlLXZhcmlhYmxlLC5zeW50YXgtdGhlbWUtZGFyayAuaGxqcy1hZGRpdGlvbntjb2xvcjojZTBjNDZjfQouc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtY29tbWVudCwuc3ludGF4LXRoZW1lLWRhcmsgLmhsanMtZGVsZXRpb24sLnN5bnRheC10aGVtZS1kYXJrIC5obGpzLW1ldGF7Y29sb3I6IzdmN2Y3Zn0KCgouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWNvbW1lbnQsLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1xdW90ZSB7Y29sb3I6IzY1NWY2ZH0KLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy12YXJpYWJsZSwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXRlbXBsYXRlLXZhcmlhYmxlLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtYXR0cmlidXRlLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtdGFnLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtbmFtZSwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXJlZ2V4cCwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWxpbmssLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1uYW1lLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtbmFtZSwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXNlbGVjdG9yLWlkLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtc2VsZWN0b3ItY2xhc3N7Y29sb3I6I2JlNDY3OH0KLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1udW1iZXIsLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1tZXRhLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtYnVpbHRfaW4sLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1idWlsdGluLW5hbWUsLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1saXRlcmFsLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtdHlwZSwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXBhcmFtc3tjb2xvcjojYWE1NzNjfQouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXN0cmluZywuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXN5bWJvbCwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWJ1bGxldHtjb2xvcjojMmE5MjkyfQouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXRpdGxlLC5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtc2VjdGlvbntjb2xvcjojNTc2ZGRifQouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWtleXdvcmQsLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1zZWxlY3Rvci10YWd7Y29sb3I6Izk1NWFlN30KLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1kZWxldGlvbiwuc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWFkZGl0aW9ue2NvbG9yOiMxOTE3MWM7ZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6MTAwJX0KLnN5bnRheC10aGVtZS1saWdodCAuaGxqcy1kZWxldGlvbntiYWNrZ3JvdW5kLWNvbG9yOiNiZTQ2Nzh9Ci5zeW50YXgtdGhlbWUtbGlnaHQgLmhsanMtYWRkaXRpb257YmFja2dyb3VuZC1jb2xvcjojMmE5MjkyfQouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLWVtcGhhc2lze2ZvbnQtc3R5bGU6aXRhbGljfQouc3ludGF4LXRoZW1lLWxpZ2h0IC5obGpzLXN0cm9uZ3tmb250LXdlaWdodDpib2xkfQoKCjwvc3R5bGU+PC9kZWZzPjxnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwwKSByb3RhdGUoMCkiIGRhdGEtc3ZnLWl0ZW0tY29udGFpbmVyLWlkPSJDbjdoVDJmbHUzIiBkYXRhLWl0ZW0taWQ9IkNuN2hUMmZsdTMiPiAgPGcgc3R5bGU9Im9wYWNpdHk6IDE7IG1peC1ibGVuZC1tb2RlOiBub3JtYWw7Ij4gPGRlZnMvPiA8ZyBmaWx0ZXI9IiI+IDxnIHN0eWxlPSJvcGFjaXR5OiAxOyI+PGc+PGc+PGc+IDwvZz4gPHBhdGggZD0iTSAzMTUgMzIwICBMIDUgMzIwIGEgNSA1IDAgMCAxIC01IC01ICBMIDAgNSAgYSA1IDUgMCAwIDEgNSAtNSAgIEwgMzE1IDAgICBhIDUgNSAwIDAgMSA1IDUgIEwgMzIwIDMxNSAgIGEgNSA1IDAgMCAxIC01IDUgWiIgc3Ryb2tlLXdpZHRoPSIwcHgiIHN0cm9rZT0iI0M3QzdDN0ZGIiBzdHJva2UtZGFzaGFycmF5PSIiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGZpbGw9Im5vbmUiLz48L2c+PC9nPjwvZz4gIDxnLz48L2c+ICA8ZyBpZD0iYW5pbWF0aW9uLWNvbnRhaW5lci1DbjdoVDJmbHUzIi8+ICAgICAgICAgPGc+PGcgdHJhbnNmb3JtPSJtYXRyaXgoMC4zNTgzNjc5NDk1NDUzMDA0LDAuOTMzNTgwNDI2NDk3MjAxNywtMC45MzM1ODA0MjY0OTcyMDE3LDAuMzU4MzY3OTQ5NTQ1MzAwNCwyNTAuODgzNTcxMzU4NDAwNDIsLTQ0LjEyNzg0MzQxNDcxNTMzKSI+ICA8ZyBzdHlsZT0ib3BhY2l0eTogMTsgbWl4LWJsZW5kLW1vZGU6IG5vcm1hbDsiPiA8ZGVmcy8+IDxnIGZpbHRlcj0iIj4gPGcgc3R5bGU9Im9wYWNpdHk6IDE7Ij48Zz48Zz48Zz4gPC9nPiA8cGF0aCBkPSJNIDE1OCAwIEEgMTU4IDE1OCAwIDAgMSAyNTAuODcwMDY5ODYyMjEwNzYgMjg1LjgyNDY4NTExMTI0MTcgTCAxNTggMTU4IFoiIHN0cm9rZS13aWR0aD0iMHB4IiBzdHJva2U9IiNDN0M3QzdGRiIgc3Ryb2tlLWRhc2hhcnJheT0iIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBmaWxsPSIjNTE4REQ3RkYiLz48L2c+PC9nPjwvZz4gIDxnLz48L2c+ICA8ZyBpZD0iYW5pbWF0aW9uLWNvbnRhaW5lci1sc0dIUXV4VnpZZyIvPiAgICAgICAgICA8L2c+PC9nPjxnIHRyYW5zZm9ybT0ibWF0cml4KC0wLjgzODY3MDU2Nzk0NTQyNCwtMC41NDQ2MzkwMzUwMTUwMjcxLDAuNTQ0NjM5MDM1MDE1MDI3MSwtMC44Mzg2NzA1Njc5NDU0MjQsMjA2LjQ1Njk4MjIwMzAwMjcyLDM3OC41NjI5MTcyNjc3NTEzKSI+ICA8ZyBzdHlsZT0ib3BhY2l0eTogMTsgbWl4LWJsZW5kLW1vZGU6IG5vcm1hbDsiPiA8ZGVmcy8+IDxnIGZpbHRlcj0iIj4gPGcgc3R5bGU9Im9wYWNpdHk6IDE7Ij48Zz48Zz48Zz4gPC9nPiA8cGF0aCBkPSJNIDE1OCAwIEEgMTU4IDE1OCAwIDAgMSAyNzkuNzQxMDkyMzU4NTc0NyAyNTguNzEyOTkwMzgwMjkzIEwgMTU4IDE1OCBaIiBzdHJva2Utd2lkdGg9IjBweCIgc3Ryb2tlPSIjQzdDN0M3RkYiIHN0cm9rZS1kYXNoYXJyYXk9IiIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgZmlsbD0iIzY1REM4QkZGIi8+PC9nPjwvZz48L2c+ICA8Zy8+PC9nPiAgPGcgaWQ9ImFuaW1hdGlvbi1jb250YWluZXItSU00bVJYcWJTaCIvPiAgICAgICAgICA8L2c+PC9nPjxnIHRyYW5zZm9ybT0ibWF0cml4KDAuOTU0MjQwMzI4NTE2Mjc3MiwtMC4yOTkwNDA3OTIyNTYwODU4LDAuMjk5MDQwNzkyMjU2MDg1OCwwLjk1NDI0MDMyODUxNjI3NzIsLTM4LjAxODQxNzA4MjAzMzM1LDU2LjQ3ODQ3MzI3MDg4OTc2NSkiPiAgPGcgc3R5bGU9Im9wYWNpdHk6IDE7IG1peC1ibGVuZC1tb2RlOiBub3JtYWw7Ij4gPGRlZnMvPiA8ZyBmaWx0ZXI9IiI+IDxnIHN0eWxlPSJvcGFjaXR5OiAxOyI+PGc+PGc+PGc+IDwvZz4gPHBhdGggZD0iTSAxNTggMCBBIDE1OCAxNTggMCAwIDEgMzE1LjY4ODIyMzA5MTY2Njk0IDE0OC4wNzkwOTc5MTQzNjg0OCBMIDE1OCAxNTggWiIgc3Ryb2tlLXdpZHRoPSIwcHgiIHN0cm9rZT0iI0M3QzdDN0ZGIiBzdHJva2UtZGFzaGFycmF5PSIiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGZpbGw9IiNDRDdCREJGRiIvPjwvZz48L2c+PC9nPiAgPGcvPjwvZz4gIDxnIGlkPSJhbmltYXRpb24tY29udGFpbmVyLW1Yb1g3MUN4TkJyIi8+ICAgICAgICAgIDwvZz48L2c+PGcgdHJhbnNmb3JtPSJtYXRyaXgoMSwwLDAsMSwyMzkuNTQ2MDk3NDI4Njk5NDMsMjU4LjIzMTI0OTUyODE2MTEzKSI+ICA8ZyBzdHlsZT0ib3BhY2l0eTogMTsgbWl4LWJsZW5kLW1vZGU6IG5vcm1hbDsiPiA8ZGVmcy8+IDxnIGZpbHRlcj0iIj4gPGcgc3R5bGU9Im9wYWNpdHk6IDE7Ii8+ICA8Zz48ZyBzdHlsZT0ib3BhY2l0eTogMTsiPjxmb3JlaWduT2JqZWN0IGlkPSJpdGVtLXRleHQtc2xvdC1CVFB0VDBFTklFcC1ib2R5IiB4PSIwIiB5PSIwIiB3aWR0aD0iMCIgaGVpZ2h0PSIwIj48ZGl2IHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiBjbGFzcz0iaXRlbS10ZXh0LWNvbnRhaW5lciIgc3R5bGU9ImNvbG9yOiByZ2IoMjUwLCAyNTAsIDI1MCk7IGZvbnQtc2l6ZTogMHB4OyBmb250LWZhbWlseTogQXJpYWwsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsgcGFkZGluZzogMHB4OyB0ZXh0LWFsaWduOiBjZW50ZXI7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGRpc3BsYXk6IHRhYmxlLWNlbGw7IGJveC1zaXppbmc6IGJvcmRlci1ib3g7IGxpbmUtaGVpZ2h0OiAxOyB3aWR0aDogMHB4OyBoZWlnaHQ6IDBweDsiPjxkaXYgY2xhc3M9Iml0ZW0tdGV4dC1lbGVtZW50IiBzdHlsZT0iZGlzcGxheTogaW5saW5lLWJsb2NrOyI+NDAlPC9kaXY+PC9kaXY+PC9mb3JlaWduT2JqZWN0PjwvZz48L2c+PC9nPiAgPGcgaWQ9ImFuaW1hdGlvbi1jb250YWluZXItQlRQdFQwRU5JRXAiLz4gICAgICAgICAgPC9nPjwvZz48ZyB0cmFuc2Zvcm09Im1hdHJpeCgxLDAsMCwxLDM0Ljc2OTQ3Mjk2NDQwOTUsMTQyLjg0NTU1MTY0NDMwNDE1KSI+ICA8ZyBzdHlsZT0ib3BhY2l0eTogMTsgbWl4LWJsZW5kLW1vZGU6IG5vcm1hbDsiPiA8ZGVmcy8+IDxnIGZpbHRlcj0iIj4gPGcgc3R5bGU9Im9wYWNpdHk6IDE7Ii8+ICA8Zz48ZyBzdHlsZT0ib3BhY2l0eTogMTsiPjxmb3JlaWduT2JqZWN0IGlkPSJpdGVtLXRleHQtc2xvdC1kbmZzSHUwdWllYS1ib2R5IiB4PSIwIiB5PSIwIiB3aWR0aD0iMCIgaGVpZ2h0PSIwIj48ZGl2IHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiBjbGFzcz0iaXRlbS10ZXh0LWNvbnRhaW5lciIgc3R5bGU9ImNvbG9yOiByZ2IoMjUwLCAyNTAsIDI1MCk7IGZvbnQtc2l6ZTogMHB4OyBmb250LWZhbWlseTogQXJpYWwsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsgcGFkZGluZzogMHB4OyB0ZXh0LWFsaWduOiBjZW50ZXI7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGRpc3BsYXk6IHRhYmxlLWNlbGw7IGJveC1zaXppbmc6IGJvcmRlci1ib3g7IGxpbmUtaGVpZ2h0OiAxOyB3aWR0aDogMHB4OyBoZWlnaHQ6IDBweDsiPjxkaXYgY2xhc3M9Iml0ZW0tdGV4dC1lbGVtZW50IiBzdHlsZT0iZGlzcGxheTogaW5saW5lLWJsb2NrOyI+MzYlPC9kaXY+PC9kaXY+PC9mb3JlaWduT2JqZWN0PjwvZz48L2c+PC9nPiAgPGcgaWQ9ImFuaW1hdGlvbi1jb250YWluZXItZG5mc0h1MHVpZWEiLz4gICAgICAgICAgPC9nPjwvZz48ZyB0cmFuc2Zvcm09Im1hdHJpeCgxLDAsMCwxLDIxNS4wMTMyMTA5NjA2NjI0LDQ2LjE5OTcwNzI5NDc2MjgzKSI+ICA8ZyBzdHlsZT0ib3BhY2l0eTogMTsgbWl4LWJsZW5kLW1vZGU6IG5vcm1hbDsiPiA8ZGVmcy8+IDxnIGZpbHRlcj0iIj4gPGcgc3R5bGU9Im9wYWNpdHk6IDE7Ii8+ICA8Zz48ZyBzdHlsZT0ib3BhY2l0eTogMTsiPjxmb3JlaWduT2JqZWN0IGlkPSJpdGVtLXRleHQtc2xvdC1Wcy1JcnRUY29Zci1ib2R5IiB4PSIwIiB5PSIwIiB3aWR0aD0iMCIgaGVpZ2h0PSIwIj48ZGl2IHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiBjbGFzcz0iaXRlbS10ZXh0LWNvbnRhaW5lciIgc3R5bGU9ImNvbG9yOiByZ2IoMjUwLCAyNTAsIDI1MCk7IGZvbnQtc2l6ZTogMHB4OyBmb250LWZhbWlseTogQXJpYWwsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsgcGFkZGluZzogMHB4OyB0ZXh0LWFsaWduOiBjZW50ZXI7IHZlcnRpY2FsLWFsaWduOiBtaWRkbGU7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGRpc3BsYXk6IHRhYmxlLWNlbGw7IGJveC1zaXppbmc6IGJvcmRlci1ib3g7IGxpbmUtaGVpZ2h0OiAxOyB3aWR0aDogMHB4OyBoZWlnaHQ6IDBweDsiPjxkaXYgY2xhc3M9Iml0ZW0tdGV4dC1lbGVtZW50IiBzdHlsZT0iZGlzcGxheTogaW5saW5lLWJsb2NrOyI+MjQlPC9kaXY+PC9kaXY+PC9mb3JlaWduT2JqZWN0PjwvZz48L2c+PC9nPiAgPGcgaWQ9ImFuaW1hdGlvbi1jb250YWluZXItVnMtSXJ0VGNvWXIiLz4gICAgICAgICAgPC9nPjwvZz48ZyB0cmFuc2Zvcm09Im1hdHJpeCgxLDAsMCwxLDAsMCkiPiAgPGcgc3R5bGU9Im9wYWNpdHk6IDE7IG1peC1ibGVuZC1tb2RlOiBub3JtYWw7Ij4gPGRlZnMvPiA8ZyBmaWx0ZXI9IiI+IDxnIHN0eWxlPSJvcGFjaXR5OiAxOyIvPiAgPGcvPjwvZz4gIDxnIGlkPSJhbmltYXRpb24tY29udGFpbmVyLTlBNlpzOFowOTl6Ii8+ICAgICAgICA8ZGVmcz48Y2xpcFBhdGggaWQ9Iml0ZW0tY2xpcC1wYXRoLTlBNlpzOFowOTl6Ij48cGF0aCBkPSJNIDAgMCAgTCAwIDAgIEwgMCAwICBMIDAgMCBaIiBzdHJva2Utd2lkdGg9IjBweCIgc3Ryb2tlPSJyZ2JhKDI1NSwgMjU1LCAyNTUsIDApIiBmaWxsPSJyZ2JhKDI1NSwgMjU1LCAyNTUsIDApIiBjbGFzcz0ic3ZnLWV2ZW50LWxheWVyIi8+PC9jbGlwUGF0aD48L2RlZnM+IDxnIHN0eWxlPSJjbGlwLXBhdGg6IHVybCgmcXVvdDsjaXRlbS1jbGlwLXBhdGgtOUE2WnM4WjA5OXomcXVvdDspOyIvPiA8L2c+PC9nPjwvZz4gPC9nPjwvZz48L3N2Zz4=

import:
    - ./src/pie-chart.sch
    - ./src/pie-chart-animations.sch

item:
  id: root
  name: Pie chart
  shape: rect
  shapeProps:
    fill: $background
    strokeColor: $strokeColor
    strokeSize: $strokeSize
    cornerRadius: $cornerRadius
  locked: false
  area:
    x: 0
    y: 0
    w: $width
    h: $height
  functions:
  - id: func-change-pie
    name: Change Pie chart
    description: Updates the values in the Pie chart with animation
    args:
    - id: arg-index
      name: values
      value: "10, 4, 5, 7, 2"
      type: string
      description: Comma separated list of values
    props:
      initScript: $changeAnimationInitScript
      script: $changeAnimationLoopScript
      endScript: $changeAnimationEndScript
      animated: true
      animationType: "animation"
      animationDuration: 0.5
      transition: "ease-out"
      inBackground: true

  childItems:
  - $-foreach: {source: "slices", it: "slice"}
    id: $`slice-${slice.id}"`
    name: $slice.name
    shape: pie_segment
    tags:
      - pie-chart-slice
    args:
      customVars:
        name   : $slice.name
        value  : $slice.value
        percent: $slice.percent
        idx    : $slice.idx
    area:
      x: $padding
      y: $padding
      w: $chartWidth
      h: $chartHeight
      r: $slice.angle

    shapeProps:
      percent: $slice.percent
      fill: {type: solid, color: $slice.color}
      strokeSize: $strokeSize
      strokeColor: $strokeColor

  - $-foreach: {source: sliceLabels, it: label}
    id: $label.id
    name: $label.text
    shape: none
    opacity: $label.opacity
    tags:
      - pie-chart-slice-label
    area:
      x: $label.x
      y: $label.y
      w: $label.w
      h: $label.h
    args:
      templateForceText: true
      customVars:
        sliceIdx: $label.sliceIdx
    textSlots:
      body:
        text: $label.text
        font: $font
        fontSize: $label.fontSize
        color: $fontColor

  - id: legend-container
    name: Legend
    shape: none
    area:
      x: $legend.x
      y: $legend.y
      w: $legend.w
      h: $legend.h
    clip: true
    childItems:
    - $-foreach: {source: legend.entries, it: entry}
      id: $`legend-entry-icon-${entry.id}`
      name: $`Icon ${entry.name}`
      shape: rect
      area:
        x: $entry.x
        y: ${ entry.y + entry.h / 2 - iconSize/2 }
        w: $iconSize
        h: $iconSize
      shapeProps:
        fill: {type: solid, color: $entry.color}
        cornerRadius: $iconCornerSize
        strokeSize: 0

    - $-foreach: {source: legend.entries, it: entry}
      id: $`legend-entry-label-${entry.id}`
      name: $`Label ${entry.name}`
      shape: none
      area:
        x: ${ entry.x + 30 }
        y: $entry.y
        w: $entry.w
        h: $entry.h
      args:
        templateForceText: true
      textSlots:
        body:
          text: $entry.name
          fontSize: $fontSize
          font: $font
          color: $fontColor
          valign: middle
          halign: left

